config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'register_event', to: 'events#register_event'
  get 'my_events', to: 'users#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations

  validates :title, presence: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 3, maximum: 1000 }

  # upcoming events  and past event
  scope :upcoming_events, -> { where('event_date >= ?', Time.zone.now) }
  scope :previous_events, -> { where('event_date < ?', Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
  VALID_EMAIL_ID = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :email, presence: true, length: { minimum: 10, maixmum: 80 }, format: { with: VALID_EMAIL_ID }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :sign_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sign_in?
    !(current_user.nil? or current_user == false)
  end

  def require_user
    return if sign_in?

    flash[:alert] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show register_event edit update destroy]
  before_action :require_user, only: %i[register_event new edit]

  def index
    @events = Event.all
    @previous_events = @events.previous_events
    @upcoming_events = @events.upcoming_events
  end

  def register_event
    if @event.attendees << @current_user
      redirect_to root_path, notice: 'Registered for the event successfully.'
    else
      redirect_to root_path, alert: 'Unable to Register for the event.'
    end
  end

  def show
    @users = @event.attendees
    return unless sign_in?

    @not_registered = true if @users.where(id: @current_user.id)[0].nil?
  end

  def new
    @event = Event.new
  end

  def edit
    redirect_to root_path if current_user.id != @event.creator_id
  end

  def create
    redirect_to login_path if session[:user_id].nil?
    @current_user = User.find(session[:user_id])
    @event = @current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :event_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    return unless sign_in?

    flash[:notice] = 'User logged already'
    redirect_to root_path
  end

  def create
    @user = User.find_by(email: (params[:session][:email]))
    if !@user.nil?
      session[:user_id] = @user.id
      flash[:notice] = 'User logged in successfully'
      redirect_to root_path
    else
      flash.now[:alert] = 'Worng Email Id'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'User logged out successfully '
  end

  private

  def session_params
    params.permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: %i[show edit update destroy]

  def show
    @created_events = @current_user.events
    @attend_events = @current_user.attended_events
    @upcoming_events = @attend_events.upcoming_events
    @prev_events = @attend_events.previous_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User was successfully created and logged in'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header_nav.html.erb
    <div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href= <%= root_path %> >Events Management</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <% if current_user %>
          <strong class="allign-middle p-3 text-primary"> <a href=  <%= my_events_path %> > <%= current_user.name %> </a> </strong>
          <a class="btn btn-outline-primary my-2 my-sm-0" href=  <%= logout_path %>> Sign out </a>
        <% else %>
          <a class="btn btn-outline-primary my-2 my-sm-0" href= <%= login_path %> > Sign in / Sign up </a>
        <% end %>
        
        
      </div>
    </div>
  </header>

app/views/application/_show_events.html.erb
    <div class="col-md-4">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"> <%= event_status %> </strong>
          <h3 class="mb-1"><%= event.title %></h3>
          <div class="mb-0 text-muted"> <%= event.event_date.to_formatted_s(:short) %> </div>
          <p class="card-text my-2 mb-auto"><%= event.description.truncate(120) %> </p>
          <a href= <%= event_path(event.id) %> class="stretched-link">Open Event details</a>
        </div>
      </div>
    </div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label :title, class: "sr-only"%>
    <%= form.text_field :title,class: "form-control my-2", placeholder: "Event Title" %>
  
    <%= form.label :description, class: "sr-only" %>
    <%= form.text_area :description,class: "form-control my-2", placeholder: "Event Description" %>

    <%= form.label :event_date, "Event date :", class: " px-2" %>
    <%= form.datetime_select :event_date, class: "form-control my-2" %>

    <%= form.submit class: "btn my-4 btn-lg btn-primary btn-block" %>

<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="jumbotron p-4 my-3 p-md-5 text-white rounded bg-secondary">
  <div class="col-md-8 px-0">
    <h1 class="display-4">Title of a longer featured blog post</h1>
    <p class="lead my-4">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    <a class="btn btn-primary btn-lg" href=<%= new_event_path %> role="button">Create Event</a>
  </div>
</div>

<h2>Upcoming Events</h2>

<div class="row my-4">
<%= render partial: 'show_events', collection: @upcoming_events, as: :event, locals: {event_status: "Upcoming"} %>
</div>


<h2>Previous Events</h2>
<div class="row my-4">
<%= render partial: 'show_events', collection: @previous_events, as: :event, locals: {event_status: "Completed"} %>
</div>

app/views/events/new.html.erb
<div class= "my-4 form-signin">
<h1 class="h3 mb-3 font-weight-normal">Create Event</h1>
<%= render 'form', event: @event %>
<h4 class="h4 mb-3 font-weight-normal">Back to Home <a class="btn btn-outline-primary my-2 my-sm-0" href= <%= root_path %> > Home </a> </h4>
</div>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>
<% if @event.event_date > Time.zone.now %>
  <% if @not_registered and current_user %>
    <h3>
    <a class="btn btn-primary btn-lg" href=<%= register_event_path(id: params[:id]) %> role="button">Register Now</a> 
    </h3>
  <% elsif current_user %>
    <h4>
    You already Registered for this event
    </h4>
  <% end %>
<% end %>

<% if  current_user and current_user.id == @event.creator_id %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Back', events_path %>

<h2 class="my-4"> Event Attendees </h2>

<ul>
  <% @users.each do |user| %>
   <li> <%= user.name %> </li>  
  <% end %> 
</ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


   <%= render 'header_nav'%>
    <% flash.each do |key , msg|%>
      <% if key === 'notice' %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% elsif key === 'alert' %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong> <%= msg %> </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

        <% user.errors.full_messages.each do |message| %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong> <%= message %> </strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        <% end %>
    </div>
  <% end %>

    <%= form.label :name , class: "sr-only" %>
    <%= form.text_field :name, class: "form-control my-2", placeholder: "Choose Username" %>


    <%= form.label :email , class: "sr-only my-2" %>
    <%= form.text_field :email, class: "form-control my-2", placeholder: "Enter your email address" %>


  <div class="actions">
    <%= form.submit "Sign up", class: "btn my-4 btn-lg btn-primary btn-block"%>
  </div>
<% end %>

app/views/users/_list_events.html.erb
<p id="notice"><%= notice %></p>

<h1>Created Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.event_date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/users/new.html.erb
<div class= "my-4 form-signin">
<h1 class="h3 mb-3 font-weight-normal">User Registration</h1>

<%= render 'form', user: @user %>
<h4 class="h4 mb-3 font-weight-normal">Existing User ? <a class="btn btn-outline-primary my-2 my-sm-0" href= <%= login_path %> >  Sign in </a> </h4>
</div>

app/views/users/show.html.erb
<h2>My Events</h2>

<div class="row my-4">
<%= render partial: 'show_events', collection: @created_events, as: :event, locals: {event_status: "My Events"} %>
</div>

<h2 class="mb-5">List of Events Registered</h2>


<h3>Upcoming Events</h3>

<div class="row my-4">
<%= render partial: 'show_events', collection: @upcoming_events, 
                as: :event, locals: {event_status: "Upcoming"} %>
</div>


<h3>Previous Events</h3>
<div class="row my-4">
<%= render partial: 'show_events', collection: @prev_events, 
                as: :event, locals: {event_status: "Completed"} %>
</div>